name: "Terraform Format and Validate"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Format and Validate"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: "Checkout Code"
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 3: Run terraform fmt to check formatting
      - name: "Terraform Format Check"
        run:  |
            terraform init
            terraform fmt .
        working-directory: src

      # Step 4: Run terraform validate to validate configuration
      - name: "Terraform Validate"
        run: terraform validate
        working-directory: src

      # Step 5: Output Success Message
      - name: "Success Message"
        if: ${{ success() }}
        run: echo "Terraform Format and Validate checks passed successfully!"