name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Packer
      run: |
        sudo apt-get update
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install packer
  
    - name: Packer Initialization
      run: |
        packer init .
      working-directory: webapp/packer
    
    - name: Create Webapp Zip
      run: |
        echo "Building application artifact..."
        zip -r webapp.zip webapp/app/ webapp/app.py webapp/requirements.txt
        echo "Artifact created: webapp.zip"
    
    - name: Packer fmt and validate
      run: |
        if ! packer fmt .; then
          exit 1
        fi
        packer validate .
      working-directory: webapp/packer