name: Web App CI

on:
  pull_request:
    branches:
      - main
  
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install -r webapp/requirements.txt

      - name: Run Tests using Unittest
        run: |
          cd webapp
          python -m unittest app.tests.test_app
        continue-on-error: false
